-- AlterTable
ALTER TABLE "Activity" ALTER COLUMN "startTime" SET DATA TYPE TEXT,
ALTER COLUMN "endTime" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "destination" ALTER COLUMN "arrivalDate" SET DATA TYPE TEXT,
ALTER COLUMN "departureDate" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "trip" ALTER COLUMN "startDate" SET DATA TYPE TEXT,
ALTER COLUMN "endDate" SET DATA TYPE TEXT;
